logging:
  level:
    tech:
      jhipster:
        lite:
          cli: INFO
spring:
  application:
    name: JHLiteCliApplication
  jackson:
    default-property-inclusion: non_null
jhlite:
  hidden-resources:
    # Disable the modules and its dependencies by slugs
    slugs: custom-jhlite
server:
  port: 8080
